apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: nginx     # Service will track Pods with this label
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: ClusterIP     # Change to NodePort / LoadBalancer as needed
